# **Tarea Nº 4**

- Fecha y hora de entrega: Domingo 12 de enero, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Armando Paredes ______
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom:

## **Mercado de autos usados**

Importa el conjunto de datos `neoauto_20240924.csv`

In [2]:
import pandas as pd
import numpy as np

In [112]:
base_prop = pd.read_csv("neoauto_20240924.csv", delimiter=",")

In [10]:
base_prop

,value,item_id,item_price,item_name,item_category,item_category_2,item_brand,item_km,item_year,item_transmission,...,item_location_province,item_tag,item_advertiser,item_credit,item_verified,item_financed_by,santander_price,item_publication_slug,item_publication_type,item_publication_type_Id
0,29200,1807331,29200.0,toyota hilux 2021,autos,Pick Up,TOYOTA,51635.0,2021,Mecánica,...,lima,Como nuevo,Erick Bazán Ubaldo,True,True,Santander,NaN,auto/usado/toyota-hilux-2021-1807331,PREMIUM,25
1,98500,1807393,98500.0,lexus lx 600 2023,autos,Camionetas Suv,LEXUS,15000.0,2023,Automática - Secuencial,...,lima,Como nuevo,Asesor Gabriel NovoCar,False,True,NaN,NaN,auto/usado/lexus-lx-600-2023-1807393,PREMIUM,25
2,16800,1739308,17800.0,bmw 520-i 2016,autos,Sedan,BMW,66000.0,2016,Automática - Secuencial,...,lima,Ocasión,Carlos Chauca,True,True,Santander,16800.0,auto/usado/bmw-520-i-2016-1739308,PREMIUM,25
3,15900,1805714,16900.0,chevrolet captiva 2021,autos,Camionetas Suv,CHEVROLET,40300.0,2021,Automática - Secuencial,...,santa,Premium,Darwin Américo Barrón Pastor,True,True,Santander,15900.0,auto/usado/chevrolet-captiva-2021-1805714,PREMIUM,25
4,12500,1806332,12500.0,dfsk glory 500 2023,autos,Camionetas Suv,DFSK,33000.0,2023,Mecánica,...,lima,Premium,GORDILLO FERNANDO,True,True,Santander,NaN,auto/usado/dfsk-glory-500-2023-1806332,PREMIUM,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4036,18000,1805535,18000.0,mini 5 puertas 2018,autos,Hatchback,MINI,32500.0,2018,Automática,...,lima,NaN,elizabeth arias,True,False,Santander,NaN,auto/usado/mini-5-puertas-2018-1805535,GRATUITO,27
4037,15000,1805482,16000.0,bmw 120i 2016,autos,Deportivo,BMW,83000.0,2016,Automática - Secuencial,...,lima,NaN,Fabrizio Canales,True,False,Santander,15000.0,auto/usado/bmw-120i-2016-1805482,GRATUITO,27
4038,9000,1805528,10000.0,volkswagen gol 2022,autos,Sedan,VOLKSWAGEN,43000.0,2022,Mecánica,...,lima,NaN,Mario Toledo Castillo,True,False,Santander,9000.0,auto/usado/volkswagen-gol-2022-1805528,GRATUITO,27
4039,30500,1805518,31500.0,bmw x5 2016,autos,Camionetas Suv,BMW,32000.0,2016,Automática - Secuencial,...,lima,NaN,SHH Hearne,True,False,Santander,30500.0,auto/usado/bmw-x5-2016-1805518,GRATUITO,27
4040,5500,1805432,5500.0,suzuki swift 2008,autos,Hatchback,SUZUKI,1600.0,2008,Automática,...,lima,NaN,Susana Patiño,False,False,NaN,NaN,auto/usado/suzuki-swift-2008-1805432,GRATUITO,27

1. ¿Cuál es el precio promedio de los autos de cada marca (`item_brand`) publicados en cada subcategoría (`item_category_2`)?

In [3]:
# Solución
precio_promedio = base_prop.groupby(["item_brand", "item_category_2"])["item_price"].mean()
print(precio_promedio)

item_brand    item_category_2
ALFA-ROMEO    Hatchback            8500.000000
              Sedan                2500.000000
ASTON MARTIN  Camionetas Suv     229000.000000
              Deportivo          169990.000000
              Sedan              149900.000000
                                     ...
VOLVO         Camionetas Suv      41801.707317
              Deportivo            8800.000000
              Hatchback           12772.500000
              Sedan               11458.333333
              Station Wagon        6100.000000
Name: item_price, Length: 202, dtype: float64

2. ¿Cuántos autos tienen más de 100,000 kilómetros (`item_km`) pero un precio (`item_price`) menor al promedio general?

In [4]:
# Solución
precio_promedio_general = base_prop["item_price"].mean()
autos_usados = base_prop[(base_prop["item_km"] > 100000) & (base_prop["item_price"] < precio_promedio_general)]
cantidad_autos = len(autos_usados)
print(cantidad_autos)

497

3. Encuentra el modelo (`item_name`) más caro y el más barato de cada marca (`item_brand`).

In [72]:
# Solución
modelo_caro = base_prop.loc[base_prop.groupby("item_brand")["item_price"].idxmax()]
modelo_barato = base_prop.loc[base_prop.groupby("item_brand")["item_price"].idxmin()]
print("modelo mas caros:")
print(modelo_caro[["item_price", "item_brand", "item_name"]])

print("modelo mas baratos")
print(modelo_barato[["item_price", "item_brand", "item_name"]])

modelo mas caros:
      item_price    item_brand                 item_name
1362      8500.0    ALFA-ROMEO       alfa-romeo 147 2006
1313    229000.0  ASTON MARTIN     aston martin dbx 2021
1208    220000.0          AUDI            audi rs 6 2024
3708         1.0        AUSTIN   austin mini cooper 1970
2317     12800.0          BAIC             baic x55 2021
...          ...           ...                       ...
3396     14000.0           SWM          swm g05 pro 2022
3582    100000.0        TOYOTA         toyota hilux 2019
1845     18900.0       TRIUMPH         triumph tr-7 1971
1373     48900.0    VOLKSWAGEN  volkswagen teramont 2023
1417     84990.0         VOLVO          volvo xc-90 2023

[73 rows x 3 columns]
modelo mas baratos
      item_price    item_brand                       item_name
2593      2500.0    ALFA-ROMEO         alfa-romeo alfasud 1982
1063    149900.0  ASTON MARTIN          aston martin db11 2017
633          0.0          AUDI              audi a3 sedan 2015
3708         1.0        AUSTIN         austin mini cooper 1970
2622      7500.0          BAIC                  baic plus 2018
...          ...           ...                             ...
3396     14000.0           SWM                swm g05 pro 2022
2690         0.0        TOYOTA  toyota land cruiser prado 2011
1845     18900.0       TRIUMPH               triumph tr-7 1971
360          0.0    VOLKSWAGEN            volkswagen bora 2015
2094      2100.0         VOLVO            volvo 850 turbo 1995

[73 rows x 3 columns]

4. Encuentra las tres marcas con mayor número de autos financiados por Santander (`item_financed_by`).

In [96]:
# Solución
autos_financiados = base_prop[base_prop["item_credit"]].groupby(["item_financed_by", "item_brand"]).size()
marcas_financiadas = autos_financiados.sort_values(ascending=False).head(3)
marcas_financiadas

item_financed_by  item_brand
Santander         BMW           296
                  TOYOTA        261
                  NISSAN        228
dtype: int64

5. Agrupa las publicaciones por tipo de transmisión (`item_transmission`) y calcula la desviación estándar del precio (`item_price`) para cada tipo.

In [100]:
# Solución
desviacion = base_prop.groupby("item_transmission")["item_price"].std()
desviacion

item_transmission
Automática                 15332.729048
Automática - Secuencial    22678.641589
Mecánica                    8137.122127
Name: item_price, dtype: float64

6. ¿Cuál es el kilometraje promedio de las publicaciones con el tag "Premium" y de las publicaciones con el tag "Como nuevo"?

In [121]:
# Solución
premiun = base_prop[base_prop["item_tag"] == "Premium"]
premiun_promedio = premiun["item_km"].mean()
como_nuevo = base_prop[base_prop["item_tag"] == "Como nuevo"]
como_nuevo_promedio = como_nuevo["item_km"].mean()
print(premiun_promedio)
print(como_nuevo_promedio)

48400.235897435894
35963.47619047619

7. ¿Cuáles son las marcas de vehículas para los que todos sus modelos fabricados en los últimos 5 años tienen al menos 5 publicaciones cada una?

In [ ]:
# Solución

## **Evolución económica internacional**

Importa el conjunto de datos de la hoja "Data" del archivo `pwt1001.xlsx`. El diccionario de variables está disponible en la hoja "Legend" del archivo Excel.

In [4]:
Data = pd.read_excel("pwt1001.xlsx")

TypeError: read_excel() got an unexpected keyword argument 'delimiter'

In [124]:
Data

                     Penn World Table, version 10.01
0                                                NaN
1  This file contains the data of PWT 10.01, as a...
2  Please refer to www.ggdc.net/pwt for extensive...
3                                                NaN
4  When using these data, please refer to the fol...
5  Feenstra, Robert C., Robert Inklaar and Marcel...

1. Calcule el PBI per cápita real ajustado por poder de paridad de compra (PPP). Use la variable de PBI que se calcula por gasto y la población. ¿Cuáles son los 10 países top?

In [ ]:
# Solución

2. Genera el ránking de los países con el mayor incremento del PBI per cápita real PPP entre los años 1990 y 2019. ¿Dónde se ubica Perú? Para los países que no tengan información para dichos años, puede utilizar datos provenientes de hasta dos años antes o después

In [ ]:
# Solución

3. Para el periodo 2010-2019, calcule el promedio del índice del capital humano. ¿Qué relación existe entre esta variable y el PBI per cápita real PPP calculado previamente? ¿y el número de horas laboradas al año por los trabajadores?

In [ ]:
# Solución

4. A partir de la variable del precio de los hogares, calcula los países y los años en los cuales se registró la mayor inflación anual para todo el periodo de tiempo disponible en la base de datos

In [ ]:
# Solución

5. ¿Cuáles son los países con la mayor cantidad de missing values en la variable de productividad total de factores a precios corrientes?

In [ ]:
# Solución

6.  Agrupa los datos por país y calcula el promedio de las horas trabajadas anuales (avh) y de la educación promedio (hc) para el periodo 2000-2020.

In [ ]:
# Solución

7.  Genere una variable que ordene a los países según el porcetaje de formación brutal de capital del 2019. Luego, estable diez grupos a manera de deciles. ¿En qué decil se ubica Péru? Vuelva a calcular usando la información de 1990. ¿El Perú se mantiene en el mismo décil o cambia?

In [ ]:
# Solución

## **Transacciones Financieras**

Importa el conjunto de datos `base_financiera.csv`

In [46]:
Datos = pd.read_csv("base_financiera.csv", delimiter=",")
Datos

      Transaction_ID Customer_ID        Date   Amount Transaction_Type Region
0               1001        C190  2023-01-01   798.68           Credit  North
1               1002        C016  2023-01-02   906.97            Debit  South
2               1003        C033  2023-01-03  1579.96            Debit  South
3               1004        C142  2023-01-04  1579.62           Credit   East
4               1005        C035  2023-01-05  3719.21            Debit  North
...              ...         ...         ...      ...              ...    ...
2025            1100        C175  2023-01-20  2137.91           Credit   East
2026            2180        C072  2023-01-20  4406.49            Debit  South
2027            1965        C022  2023-01-05   676.48            Debit  North
2028            1793        C107  2023-02-02  4099.63            Debit  North
2029            1030        C049  2023-01-30   330.36           Credit  North

[2030 rows x 6 columns]

8. Filtra todas las transacciones de tipo "Debit" en las que el monto sea mayor a 200, y calcula el monto total de esas transacciones. Además, determina cuántos clientes únicos realizaron esas transacciones.

In [47]:
# Solución
montos = Datos[(Datos["Transaction_Type"] == "Debit") & (Datos["Amount"] > 200)]
print(montos)
montos_total = montos["Amount"].sum()
print("la suma de todos los montos es",montos_total)
cliente_unico = montos["Customer_ID"].nunique()
print("la cantidad de clientes que realizaron las operaciones fueron", cliente_unico)

      Transaction_ID Customer_ID        Date   Amount Transaction_Type Region
1               1002        C016  2023-01-02   906.97            Debit  South
2               1003        C033  2023-01-03  1579.96            Debit  South
4               1005        C035  2023-01-05  3719.21            Debit  North
5               1006        C078  2023-01-06  3127.58            Debit   West
8               1009        C031  2023-01-09  4044.73            Debit   West
...              ...         ...         ...      ...              ...    ...
2016            1747        C171  2023-01-27  2498.66            Debit   West
2021            2665        C072  2023-01-25  3060.79            Debit  South
2026            2180        C072  2023-01-20  4406.49            Debit  South
2027            1965        C022  2023-01-05   676.48            Debit  North
2028            1793        C107  2023-02-02  4099.63            Debit  North

[1094 rows x 6 columns]
la suma de todos los montos es 2847871.75
la cantidad de clientes que realizaron las operaciones fueron 200

9. Identifica las transacciones con valores nulos en la columna (`Amount`) . Rellena esos valores con la mediana de los montos por tipo de transacción (`Transaction_Type`) y luego calcula el monto total de transacciones por región (`region`) .

In [45]:
# Solución
print(Datos[Datos["Amount"].isnull()])
mediana = Datos.groupby("Transaction_Type")["Amount"].median()
print(mediana)
Datos["Amount"] = Datos.apply(lambda row: mediana[row["Transaction_Type"]] if pd.isnull(row["Amount"]) else row["Amount"], axis=1)
print(Datos)
monto_region = Datos.groupby("Region")["Amount"].sum()
print(monto_region)

      Transaction_ID Customer_ID        Date  Amount Transaction_Type Region
34              1035        C043  2023-02-04     NaN            Debit   East
40              1041        C051  2023-01-01     NaN           Credit   West
60              1061        C086  2023-01-21     NaN            Debit   East
66              1067        C179  2023-01-27     NaN           Credit   East
82              1083        C076  2023-01-03     NaN            Debit  South
...              ...         ...         ...     ...              ...    ...
1944            2945        C134  2023-01-25     NaN           Credit   West
1967            2968        C150  2023-01-08     NaN            Debit  South
2015            1276        C047  2023-02-05     NaN           Credit   West
2018            2647        C068  2023-01-07     NaN            Debit  North
2023            2084        C123  2023-01-04     NaN            Debit   East

[113 rows x 6 columns]
Transaction_Type
Credit    2424.42
Debit     2461.04
Name: Amount, dtype: float64
      Transaction_ID Customer_ID        Date   Amount Transaction_Type Region
0               1001        C190  2023-01-01   798.68           Credit  North
1               1002        C016  2023-01-02   906.97            Debit  South
2               1003        C033  2023-01-03  1579.96            Debit  South
3               1004        C142  2023-01-04  1579.62           Credit   East
4               1005        C035  2023-01-05  3719.21            Debit  North
...              ...         ...         ...      ...              ...    ...
2025            1100        C175  2023-01-20  2137.91           Credit   East
2026            2180        C072  2023-01-20  4406.49            Debit  South
2027            1965        C022  2023-01-05   676.48            Debit  North
2028            1793        C107  2023-02-02  4099.63            Debit  North
2029            1030        C049  2023-01-30   330.36           Credit  North

[2030 rows x 6 columns]
Region
East     1269409.53
North    1321224.96
South    1208300.23
West     1233552.50
Name: Amount, dtype: float64

10. Busca transacciones duplicadas considerando las columnas (`Customer_ID`) y (`Date`). Elimina los duplicados manteniendo solo la primera ocurrencia. Luego, agrupa las transacciones restantes por (`Customer_ID`) y calcula el monto promedio y la cantidad de transacciones por cliente.

In [55]:
# Solución
sin_duplicados = Datos.drop_duplicates(subset=["Customer_ID", "Date"])
agrupacion_promedio = sin_duplicados.groupby("Customer_ID")["Amount"].mean()
agrupacion_cantidad = sin_duplicados.groupby("Customer_ID").size()
print("cantidad de veces que cada cliente hace una transaccion:")
print(agrupacion_cantidad)
print("monto promedio de las transacciones:")
print(agrupacion_promedio)

cantidad de veces que cada cliente hace una transaccion:
Customer_ID
C001    17
C002     9
C003    14
C004     7
C005     6
        ..
C196    10
C197    14
C198    12
C199     5
C200     5
Length: 200, dtype: int64
monto promedio de las transacciones:
Customer_ID
C001    3334.711875
C002    1881.827778
C003    3102.125000
C004    3053.882000
C005    3364.053333
           ...
C196    2566.555000
C197    2530.674286
C198    2484.925000
C199    3062.287500
C200    2130.977500
Name: Amount, Length: 200, dtype: float64